### ISSUE TITLE
Unable to run npm install successfully as mentioned in code pattern

### ISSUE THREAD

**Issue by ragdeshp** [IBM/BlockchainSmartContractTrading-CompositeJourney#13]
When we ran the npm install, there were errors mentioning that python version needs to be between 2.5 and 3, so then ran the npm install with python version as below and got the following error:

product-auction@0.0.1 prepublish /Users/raghavendradeshpande/Documents/2018/May/BlockchainSmartContractTrading-CompositeJourney
> mkdirp ./dist && composer archive create --sourceType dir --sourceName . -a ./dist/product-auction.bna

sh: composer: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! product-auction@0.0.1 prepublish: `mkdirp ./dist && composer archive create --sourceType dir --sourceName . -a ./dist/product-auction.bna`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the product-auction@0.0.1 prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/raghavendradeshpande/.npm/_logs/2018-05-18T14_46_29_686Z-debug.log

Can you please provide the resolution for this asap.

**Comment by ljbennett62** [comment]
@ragdeshp - you need to install with Python 2.7.  virtualenv is for segregating python versions and environments, it specifically exists to eliminate conflicts.  example
`pip install virtualenv`
`virtualenv env27 --python=python2.7`
