### ISSUE TITLE
Additional details are needed

### ISSUE THREAD

**Issue by odrodrig** [IBM/BlockchainSmartContractTrading-CompositeJourney#14]
Steps for deploying the .bna file to the web playground should be updated to include specifics on what to click on e.g. "click on **Deploy a new business network** then click on **drop here to upload or browse** .... "

**Comment by ljbennett62** [comment]
@odrodrig - Hi Oliver - I have add the additional detail - please review and if you feel it is complete - go ahead and close this issue. tx
