### ISSUE TITLE
Carification on steps for creating identities 

### ISSUE THREAD

**Issue by odrodrig** [IBM/BlockchainSmartContractTrading-CompositeJourney#15]
In section 2 the steps on creating identities for the member and seller participants is not really clear. Some additional information would be helpful. Also, there are multiple references to a "Wallet Tab" which is not apparent when trying to switch identities.

**Comment by ljbennett62** [comment]
@odrodrig - Hi Oliver - I have add the additional detail - please review and if you feel it is complete - go ahead and close this issue. tx
