### ISSUE TITLE
Transaction Process logic is non-deterministic

### ISSUE THREAD

**Issue by davidkel** [IBM/BlockchainSmartContractTrading-CompositeJourney#16]
This line
https://github.com/IBM/BlockchainSmartContractTrading-CompositeJourney/blob/9fe5ca3a9265152b06e01dfa16ce59e777e98bb7/lib/logic.js#L114

(ie the use of Math.random() to generate an identifier)

makes the transaction non-deterministic. This means you get away with it on a fabric network with a single organisation, but it would fail if you had more than 1 organisation and an endorsement policy that requires at least 2 organisations to endorse as the result generated by the peers of each organisation would almost always never agree.

**Comment by ljbennett62** [comment]
this issue was fixed
