### ISSUE TITLE
Clarification on Step 2 (Deploy the Business Network Archive using Composer Playground)

### ISSUE THREAD

**Issue by Bataahai** [IBM/BlockchainSmartContractTrading-CompositeJourney#4]
Hi,

I have created the file product-auction.bna and imported it to composer playground (http://composer-playground.mybluemix.net).
Now I'm trying to add the Access Control.
But the guide is not clear to me:

1. There is no button called "+Add to Wallet" shown in your first image. 
2. The window (with title "Identity Issued") shown in the 3rd image does not appear.
3. How can I have memberA, memberB in the lists shown in 4th image.

Could you please make me clear on this.
Thank you.

**Comment by ljbennett62** [comment]
@Bataahai - the UI has been changed - see the new updated README.  The cards are automatically added - so no need to separately do so. BTW - the code has been updated to Hyperledger V1.1 / Composer 19.0.0.
